// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}


function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR or localStorage/window for runtime configuration
  const localUrl = typeof window !== 'undefined' ? (localStorage.getItem('supabase_project_url') || (window as any).__SUPABASE_URL__) : undefined;
  const localKey = typeof window !== 'undefined' ? (localStorage.getItem('supabase_anon_key') || (window as any).__SUPABASE_ANON_KEY__) : undefined;

  let SUPABASE_URL = import.meta.env['VITE_SUPABASE_URL'] || process.env['SUPABASE_URL'] || localUrl;
  let SUPABASE_PUBLISHABLE_KEY = import.meta.env['VITE_SUPABASE_PUBLISHABLE_KEY'] || process.env['SUPABASE_PUBLISHABLE_KEY'] || localKey;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    if (typeof window === 'undefined') {
      try {
        const fs = require('node:fs');
        const path = require('node:path');
        const storePath = path.join(process.cwd(), 'data', 'account-keys.json');
        if (fs.existsSync(storePath)) {
          const parsed = JSON.parse(fs.readFileSync(storePath, 'utf-8'));
          SUPABASE_URL = SUPABASE_URL || parsed.global?.supabase_project_url;
          SUPABASE_PUBLISHABLE_KEY = SUPABASE_PUBLISHABLE_KEY || parsed.global?.supabase_anon_key;
        }
      } catch {}
    }
  }

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase configuration: ${missing.join(', ')}. Ampidiro ao amin'ny Paramètres (/settings) ireo clé ireo.`;
    console.warn(`[Supabase] ${message}`);
    // Return a dummy fallback or throw when invoked
    return createClient<Database>('https://placeholder.supabase.co', 'placeholder-anon-key', {
      auth: { persistSession: false },
    });
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

